### ISSUE TITLE
Intensity Parameter

### ISSUE THREAD

**Issue by torchlidar** [pclucas14/processed-kitti-lidar#1]
First of all, thank you so much for providing great code!

I think that the intensity is excluded from the files provided in advance in this data, can you share the code that processes like this?
What can we do if we want to get the ultimate adaptation, the intensity parameter?

I'll wait for your answer.
Thank you for that.

**Comment by pclucas14** [comment]
Hi,

yes I unfortunately discarded the intensity information. I would need to check in old code to see if I still have it, will let you know.

-Lucas

**Comment by torchlidar** [comment]
Hello,
Thank you so much for your kindness.
Then I'll wait for you :)


Thank you.

**Comment by pclucas14** [comment]
Hi, 

the utilities I used are somewhere here https://github.com/pclucas14/Lidar/blob/master/utils.py#L31. 

In all honesty, the code is a mess and you're probably better off writing your own code from scratch to that you understand it. 

Best of luck!
